- name: Install redis repo file
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
    state: installed
    disable_gpg_check: yes

- name: Install Redis 6.2
  ansible.builtin.dnf:
    name: '@redis:remi-6.2'
    state: installed

- name: Changing the listener address from 120.0.0.1 to 0.0.0.0
  replace:
    path: /etc/redis.conf
    regexp: 120.0.0.1
    replace: 0.0.0.0

- name: Enabling and restarting the redis
  systemd:
    name: redis
    state: restarted
    enabled: true