- name: Install nginx
  yum:
    name: nginx
    state: installed

- name: Deleting old content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: creating the new directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

