- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Deleting old content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: creating application directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download dependencies of frontend
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Coping the configuration file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
    remote_src: yes