- name: Setup Erlang repos
  shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash

- name: Setup rabbitmq repos
  shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Install Erlang and rabbitmq
  yum:
    name:
      - erlang
      - rabbitmq-server
    state: installed

- name: Enabling and restarting the rabbitmq
  systemd:
    name: rabbitmq-server
    state: restarted
    enabled: true

- name: Add Application User and set permissions
  community.rabbitmq.rabbitmq_user:
    user: "{{ lookup('amazon.aws.aws_ssm', '{{env}}.{{component}}.amqp_user', region = 'us-east-1') }}"
    password: "{{ lookup('amazon.aws.aws_ssm', '{{env}}.{{component}}.amqp_pass', region = 'us-east-1') }}"
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present
