- name: mongodb setup
  when: schema_type == "mongo"
  block:
    - name: setup mongodb repo file
      copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mongodb
      yum:
        name: mongodb-org-shell
        state: installed

    - name: load schema
      shell: mongo --host mongodb-dev.devops71.tech </app/schema/catalogue.js