- name: mongodb setup
  when: schema_type == "mongo"
  block:
    - name: setup mongodb repo file
      template:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo

    - name: install mongodb
      yum:
        name: mongodb-org-shell
        state: installed

    - name: load schema
      shell: mongo --host mongodb-dev.devops71.tech < /app/schema/{{ component }}.js

- name: MySQL Schema setup
  when: schema_type == "mysql"
  block:
    - name: Install MySQL Client
      ansible.builtin.yum:
        name: mysql
        state: installed

    - name: load schema
      shell: mysql -h mysql-dev.devops71.tech -uroot -p{{ lookup('amazon.aws.aws_ssm', '{{env}}.{{component}}.password < /app/schema/{{component}}.sql