- name: systemd setup
  copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: Enable and restart the service
  systemd:
    name: catalogue
    enabled: true
    state: restarted
    daemon_reload: true

