- name: systemd setup
  template:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{ component }}.service

- name: Enable and restart the {{ component }} service
  systemd:
    name: "{{ component }}"
    enabled: true
    state: restarted
    daemon_reload: true

